-- 教材请求状态；旧消息保留 NULL。每个请求至多一条问题和一条回答。
SET @stage20_exists = (SELECT COUNT(*) FROM information_schema.columns WHERE table_schema = DATABASE() AND table_name = 'chat_history' AND column_name = 'rag_request_id');
SET @stage20_sql = IF(@stage20_exists = 0, 'ALTER TABLE chat_history ADD COLUMN rag_request_id VARCHAR(36) CHARACTER SET ascii COLLATE ascii_bin NULL', 'SELECT 1');
PREPARE stage20_statement FROM @stage20_sql;
EXECUTE stage20_statement;
DEALLOCATE PREPARE stage20_statement;
SET @stage20_exists = (SELECT COUNT(*) FROM information_schema.columns WHERE table_schema = DATABASE() AND table_name = 'chat_history' AND column_name = 'rag_status');
SET @stage20_sql = IF(@stage20_exists = 0, 'ALTER TABLE chat_history ADD COLUMN rag_status VARCHAR(16) NULL', 'SELECT 1');
PREPARE stage20_statement FROM @stage20_sql;
EXECUTE stage20_statement;
DEALLOCATE PREPARE stage20_statement;
SET @stage20_exists = (SELECT COUNT(*) FROM information_schema.columns WHERE table_schema = DATABASE() AND table_name = 'chat_history' AND column_name = 'rag_attempt');
SET @stage20_sql = IF(@stage20_exists = 0, 'ALTER TABLE chat_history ADD COLUMN rag_attempt INT NULL', 'SELECT 1');
PREPARE stage20_statement FROM @stage20_sql;
EXECUTE stage20_statement;
DEALLOCATE PREPARE stage20_statement;
SET @stage20_exists = (SELECT COUNT(*) FROM information_schema.columns WHERE table_schema = DATABASE() AND table_name = 'chat_history' AND column_name = 'rag_context');
SET @stage20_sql = IF(@stage20_exists = 0, 'ALTER TABLE chat_history ADD COLUMN rag_context JSON NULL', 'SELECT 1');
PREPARE stage20_statement FROM @stage20_sql;
EXECUTE stage20_statement;
DEALLOCATE PREPARE stage20_statement;
SET @stage20_exists = (SELECT COUNT(*) FROM information_schema.columns WHERE table_schema = DATABASE() AND table_name = 'chat_history' AND column_name = 'rag_retry_after');
SET @stage20_sql = IF(@stage20_exists = 0, 'ALTER TABLE chat_history ADD COLUMN rag_retry_after DATETIME(6) NULL', 'SELECT 1');
PREPARE stage20_statement FROM @stage20_sql;
EXECUTE stage20_statement;
DEALLOCATE PREPARE stage20_statement;
SET @stage20_exists = (SELECT COUNT(*) FROM information_schema.statistics WHERE table_schema = DATABASE() AND table_name = 'chat_history' AND index_name = 'uk_chat_rag_request_role');
SET @stage20_sql = IF(@stage20_exists = 0, 'ALTER TABLE chat_history ADD UNIQUE INDEX uk_chat_rag_request_role (user_id, conversation_id, rag_request_id, role)', 'SELECT 1');
PREPARE stage20_statement FROM @stage20_sql;
EXECUTE stage20_statement;
DEALLOCATE PREPARE stage20_statement;
